## **抓取2021 上櫃股票股價**

In [ ]:
import sqlite3
import os
import requests
import time
import datetime
import json
import pandas as pd
import numpy as np
from io import StringIO
import matplotlib.pyplot as plt
headers = {'User-Agent': 'Chrome/66.0.3359.181 Safari/537.36'
                            'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
                             'AppleWebKit/537.36 (KHTML, like Gecko) '}


tpex_list =[]
tpex_list109 =[]

股票代號 =3169#@param {type:"integer"}
開始月份 = 1 #@param {type:"integer"}
結束月份 =  9#@param {type:"integer"}

for j in range (9,13): 
    try:
      url = f"https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_info/st43_result.php?l=zh-tw&d=109/{j}&stkno={股票代號}"
      r = requests.get(url,headers=headers)
      r.encoding = 'utf-8'
      df =r.json()['aaData']
      tpex_list109.extend(df)
      time.sleep(0.35)
    except:
      print('上櫃沒這個號碼')
if tpex_list109: 
  df109 = pd.DataFrame(tpex_list109)
  df109.columns = ['date','成交股數','成交金額','開盤價','最高價','最低價','收盤價','漲跌','成交筆數']
  df109 = df109.drop(columns=['漲跌'])
  df109['stock_id'] = 股票代號
  df109['成交股數'] =df109['成交股數'].str.replace(",","")
  df109['成交股數'] =df109['成交股數'].astype(int)
  df109['成交金額'] =df109['成交金額'].str.replace(",","")
  df109['成交金額'] =df109['成交金額'].astype(int)
  df109['開盤價'] =df109['開盤價'].astype(float)
  df109['最高價'] =df109['最高價'].astype(float)
  df109['最低價'] =df109['最低價'].astype(float)
  df109['收盤價'] =df109['收盤價'].astype(float)
  df109['成交筆數'] =df109['成交筆數'].str.replace(",","")
  df109['成交筆數'] =df109['成交筆數'].astype(int)
  df109['date'] = df109['date'].str.replace("/","-")
  #109+1911 轉換西元年
  df109['date'] = df109['date'].str.replace("109","2020")
  df109['date'] = pd.to_datetime(df109['date'])
  df109 = df109[['stock_id','date','成交股數','成交筆數','成交金額','開盤價','最高價','最低價','收盤價']]

for j in range (開始月份,結束月份+1): 
    try:
      url = f"https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_info/st43_result.php?l=zh-tw&d=110/{j}&stkno={股票代號}"
      r = requests.get(url,headers=headers)
      r.encoding = 'utf-8'
      df =r.json()['aaData']
      tpex_list.extend(df)
      time.sleep(0.35)
    except:
      print('上櫃沒這個號碼')
if tpex_list: 
  df110 = pd.DataFrame(tpex_list)
  df110.columns = ['date','成交股數','成交金額','開盤價','最高價','最低價','收盤價','漲跌','成交筆數']
  df110 = df110.drop(columns=['漲跌'])
  df110['stock_id'] = 股票代號
  df110['成交股數'] =df110['成交股數'].str.replace(",","")
  df110['成交股數'] =df110['成交股數'].astype(int)
  df110['成交金額'] =df110['成交金額'].str.replace(",","")
  df110['成交金額'] =df110['成交金額'].astype(int)
  df110['開盤價'] =df110['開盤價'].astype(float)
  df110['最高價'] =df110['最高價'].astype(float)
  df110['最低價'] =df110['最低價'].astype(float)
  df110['收盤價'] =df110['收盤價'].astype(float)
  df110['成交筆數'] =df110['成交筆數'].str.replace(",","")
  df110['成交筆數'] =df110['成交筆數'].astype(int)
  df110['date'] = df110['date'].str.replace("/","-")
  #109+1911 轉換西元年
  df110['date'] = df110['date'].str.replace("110","2021")
  df110['date'] = pd.to_datetime(df110['date'])
  df110 = df110[['stock_id','date','成交股數','成交筆數','成交金額','開盤價','最高價','最低價','收盤價']]
  df110 = pd.concat([df109,df110],axis=0)
  df110.set_index('date', inplace=True)
  df110.index = pd.to_datetime(df110.index, format='%Y-%m-%d',infer_datetime_format=True)
else:
  print('沒東西喔')
df110

            stock_id  成交股數  成交筆數    成交金額     開盤價    最高價     最低價     收盤價
date
2020-09-01      3169    93    98    3440   37.00   37.4   36.60   37.40
2020-09-02      3169    49    52    1813   37.80   37.8   37.05   37.10
2020-09-03      3169    91    80    3350   37.10   37.1   36.65   36.75
2020-09-04      3169   102   124    3624   34.95   35.9   34.95   35.85
2020-09-07      3169   133   109    4756   35.70   36.3   35.60   35.65
...              ...   ...   ...     ...     ...    ...     ...     ...
2021-09-15      3169  1704  1341  223569  134.00  135.5  128.50  131.00
2021-09-16      3169   805   645  105695  131.50  133.5  130.00  131.00
2021-09-17      3169  1415  1201  190925  131.50  137.5  130.00  137.00
2021-09-22      3169   998   759  134096  131.50  137.5  131.00  135.50
2021-09-23      3169   949  1200  128475  138.00  138.5  133.50  133.50

[260 rows x 8 columns]

## **這個要安裝按下去**

In [ ]:
!pip install talib-binary > log.txt
!pip install plotly==4.14.1
!pip install matplotlib==3.2.2

Collecting plotly==4.14.1
  Downloading plotly-4.14.1-py2.py3-none-any.whl (13.2 MB)
     |████████████████████████████████| 13.2 MB 4.8 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly==4.14.1) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly==4.14.1) (1.3.3)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1
Successfully installed plotly-4.14.1
Requirement already satisfied: matplotlib==3.2.2 in /usr/local/lib/python3.7/dist-packages (3.2.2)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.2.2) (1.19.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.2.2) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.2.2) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.2.2) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.2.2) (3.0.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib==3.2.2) (1.15.0)

## **上櫃 非波那契+EMA+LongShort**

In [ ]:
import talib
import plotly.graph_objects as go
import pandas as pd
from plotly.subplots import make_subplots

ap = (df110['最高價']+df110['最低價']+df110['收盤價'])/3 
esa = talib.EMA(ap, 10)
d = talib.EMA(abs(ap - esa), 10)
ci = (ap - esa) / (0.015 * d)
tci = talib.EMA(ci, 21)
wt1 = tci
wt2 = talib.SMA(wt1,4)

ema7 = talib.EMA(df110['收盤價'],7)
ema21 = talib.EMA(df110['收盤價'],21)
ema56 = talib.EMA(df110['收盤價'],56)
ema147 = talib.EMA(df110['收盤價'],147)
最高股價 =  220#@param {type:""}
最低股價 =  61#@param {type:""}
## @markdown * **控制Ｋ棒 EMA大小**
# Y軸左上間距 =   200#@param {type:""}
# Y軸左下間距 =   115#@param {type:""}
## @markdown * **控制Lon Shrot Ｍacd大小**
# Y軸右上間距 =  200 #@param {type:""}
# Y軸右下間距 =  -200 #@param {type:""}
##@markdown * **控制X軸時間間距**
# 時間開始 = '2021-01-01' #@param {type:"date"}
# 時間結束 = '2021-07-12' #@param {type:"date"}
#@markdown <br>

#@markdown <h3> ---多 </h3>
#@markdown * EMA7 > EMA21 ▲ <br>
#@markdown * EMA7 > EMA21 & EMA21 > 56 ☀ <br>
#@markdown * EMA21 > EMA56 & EMA56 > 147 ✈ <br>
#@markdown <br>
#@markdown <h3> ---空 </h3>
#@markdown * EMA21 > EMA7 ▼ <br>
#@markdown * EMA21 > EMA7 & EMA56 > 21 🚏 <br>
#@markdown * EMA56 > EMA21 & EMA56 > 147 ☠️ <br>



# Fibonacci Levels considering original trend as upward move
diff = 最高股價 - 最低股價
level6 = 最低股價 + (1.618 * diff)
level5 = 最低股價 + (1.414 * diff)
level1 = 最高股價 - 0.236 * diff
level2 = 最高股價 - 0.382 * diff
level3 = 最高股價 - 0.5 * diff
level4 = 最高股價 - 0.618 * diff

# diff = 最高股價 - 最低股價
# level6 = 最高股價 - (1.618 * diff)
# level5 = 最高股價 - (1.414 * diff)
# level1 = 最低股價 + 0.236 * diff
# level2 = 最低股價 + 0.382 * diff
# level3 = 最低股價 + 0.5 * diff
# level4 = 最低股價 + 0.618 * diff


df110['60'] = 60
df110['53'] = 53
df110['-60'] = -60
df110['-53'] = -53
# df110['100'] = Y軸左上間距
# df110['-100'] = Y軸左下間距

df110['ema7'] = ema7
df110['ema21'] = ema21
df110['ema56'] = ema56
df110['ema147'] = ema147



fig = make_subplots(specs=[[{'secondary_y': True}]])

fig.add_trace(go.Candlestick(x=df110.index,
                open=df110['開盤價'], high=df110['最高價'],
                low=df110['最低價'], close=df110['收盤價'])
               )

fig.add_trace(go.Scatter(y=df110['ema7'],x=df110.index, 
                    mode='lines',
                    name='ema7',
                    line = go.scatter.Line(color = "#8600FF")
                    )
             )
fig.add_trace(go.Scatter(y=df110['ema21'],x=df110.index, 
                    mode='lines',
                    name='ema21',
                    line = go.scatter.Line(color = "#2828FF")
                    )
             )
fig.add_trace(go.Scatter(y=df110['ema56'],x=df110.index, 
                    mode='lines',
                    name='ema56',
                    line = go.scatter.Line(color = "#FF8000")
                    )
             )
fig.add_trace(go.Scatter(y=df110['ema147'],x=df110.index, 
                    mode='lines',
                    name='ema147',
                    line = go.scatter.Line(color = "#AD5A5A")
                    )
             )

fig.add_trace(go.Scatter(y=wt1,  x=wt1.index, 
                    mode='lines',
                    name='long',
                    line = go.scatter.Line(color = "#02DF82")
                    ),secondary_y=True
             )
fig.add_trace(go.Scatter(y=wt2,  x=wt1.index, 
                    mode='lines',
                    name='short',
                    line = go.scatter.Line(color = "#F00078")
                    ),secondary_y=True
             )

# fill area between trace0 and trace1
fig.add_trace(go.Scatter(x=df110.index,y=(wt1-wt2),
                    fill='toself', 
                    mode='lines', 
                    line_color='#84C1FF'),secondary_y=True
             )

fig.add_trace(go.Scatter(x=df110.index,y=df110['60'], 
                    mode='lines',
                    name='60',
                    line=dict(color='#FF5151', width=1)
                    ),secondary_y=True
             )
fig.add_trace(go.Scatter(x=df110.index,y=df110['53'], 
                    mode='lines',
                    name='53',
                    line=dict(color='#FF5151', width=3, dash='dot'),
                    ),secondary_y=True
             )

fig.add_trace(go.Scatter(x=df110.index,y=df110['-60'], 
                    mode='lines',
                    name='-60',
                    line=dict(color='#007500', width=1)
                    ),secondary_y=True
             )
fig.add_trace(go.Scatter(x=df110.index,y=df110['-53'], 
                         #mode='lines+markers',
                    mode='lines',
                    name='-53',
                    line=dict(color='#007500', width=3, dash='dot'),
                    ),secondary_y=True
             )


# fig.add_trace(go.Scatter(x=df110.index,y=df110['100'], 
#                     mode='lines',
#                     name='',
#                     line=dict(color='#FFFFFF', width=0.1)
#                     ),secondary_y=True
#              )
# fig.add_trace(go.Scatter(x=df110.index,y=df110['-100'], 
#                     mode='lines',
#                     name='',
#                     line=dict(color='#FFFFFF', width=0.1)
#                     ),secondary_y=True
#              )

fig.add_hline(y=level5,line_color="orange" ,annotation_text=str(level5)+"(1.414)", annotation_position="top right") 
fig.add_hline(y=最低股價,line_color="orange" ,annotation_text=str(最低股價)+"(0)", annotation_position="top right")
fig.add_hline(y=level1,line_color="gray")
fig.add_hline(y=level2,line_color="gray" ,annotation_text=str(level2)+"(0.382)", annotation_position="top right")
fig.add_hline(y=level3,line_color="gray")
fig.add_hline(y=level4,line_color="gray" ,annotation_text=str(level4)+"(0.618)", annotation_position="top right")
fig.add_hline(y=最高股價,line_color="orange" ,annotation_text=str(最高股價)+"(1)", annotation_position="top right") #bottom right


# fig.update_layout(yaxis_range=[Y軸左下間距, Y軸左上間距])
# fig.update_xaxes(range=[時間開始,時間結束])

fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()

## **邪教團_集中度_DashBoard**

In [ ]:
import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

股票代號 =  3169#@param {type:""}
#K棒數 =  80#@param {type:""}

url =f'https://fubon-ebrokerdj.fbs.com.tw/Z/ZC/ZCW/CZKC1.djbcd?b=D&c=60&a={股票代號}'
r = requests.get(url, timeout=15).text.split(' ')

df = pd.DataFrame(r)
df = df[0].str.split(',',expand=True)
df = df.T
df[19] = df[19].str.replace(';','')
df.fillna(value=np.nan, inplace=True)
df.fillna(0, inplace=True)
df[5] = pd.to_numeric(df[5], errors='coerce')
df[6] = pd.to_numeric(df[6], errors='coerce')
df[7] = pd.to_numeric(df[7], errors='coerce')
df[8] = pd.to_numeric(df[8], errors='coerce')
df[9] = pd.to_numeric(df[9], errors='coerce')
df[10] = pd.to_numeric(df[10], errors='coerce')
df[14] = df[8]+df[9]+df[10]
df[15] = pd.to_numeric(df[15], errors='coerce')
df[17] = pd.to_numeric(df[17], errors='coerce')
df[19] = pd.to_numeric(df[19], errors='coerce')
df[20] = pd.to_numeric(df[20], errors='coerce')
df[21] = pd.to_numeric(df[21], errors='coerce')

df = df.rename(columns={0:'交易日',4:'收盤',5:'成交量',6:'融資餘張',7:'融券餘張',8:'外資持股',9:'投信持股',10:'自營持股'
                  ,14:'法人持股',15:'主力買賣超',17:'融資使用率',19:'外資買賣超',20:'投信買賣超',21:'自營買賣超'})
#原始資料star
dfO = df
dfO = dfO.drop([1,2,3,11,12,13,16,18,22],axis=1)
#原始資料End
df['成交量']  = df['成交量'].replace(0, np.nan)
df['成交量']  =df['成交量']-df['成交量'].min()
df['成交量']  =df['成交量']/df['成交量'].max()*100
df['融資餘張']  = df['融資餘張'].replace(0, np.nan)
df['融資餘張']  =df['融資餘張']-df['融資餘張'].min()
df['融資餘張']  =df['融資餘張']/df['融資餘張'].max()*100
df['融券餘張']  = df['融券餘張'].replace(0, np.nan)
df['融券餘張']  =df['融券餘張']-df['融券餘張'].min()
df['融券餘張']  =df['融券餘張']/df['融券餘張'].max()*100
df['外資持股']  = df['外資持股'].replace(0, np.nan)
df['外資持股']  =df['外資持股']-df['外資持股'].min()
df['外資持股']  =df['外資持股']/df['外資持股'].max()*100
df['投信持股']  = df['投信持股'].replace(0, np.nan)
df['投信持股']  =df['投信持股']-df['投信持股'].min()
df['投信持股']  =df['投信持股']/df['投信持股'].max()*100
df['自營持股']  = df['自營持股'].replace(0, np.nan)
df['自營持股']  =df['自營持股']-df['自營持股'].min()
df['自營持股']  =df['自營持股']/df['自營持股'].max()*100
df['法人持股']  = df['法人持股'].replace(0, np.nan)
df['法人持股']  =df['法人持股']-df['法人持股'].min()
df['法人持股']  =df['法人持股']/df['法人持股'].max()*100
df['融資使用率']  = df['融資使用率'].replace(0, np.nan)
df['融資使用率']  =df['融資使用率']-df['融資使用率'].min()
df['融資使用率']  =df['融資使用率']/df['融資使用率'].max()*100
df = df.drop([1,2,3,11,12,13,16,18,22],axis=1)
def style_negative(v, props='',subset=''):
    return props if v < 0 else None
df = df.style.applymap(style_negative, props='color:red;',subset=['主力買賣超'])\
      .applymap(style_negative, props='color:red;',subset=['外資買賣超'])\
      .applymap(style_negative, props='color:red;',subset=['投信買賣超'])\
      .applymap(style_negative, props='color:red;',subset=['自營買賣超'])
df

In [ ]:
#@markdown <h3> 匯出檔案 </h3>
from google.colab import files
df.to_excel(f'{股票代號}_Energy_Power.xlsx',index=False) 
files.download(f'{股票代號}_Energy_Power.xlsx')

In [ ]:
#@markdown <h3> 匯出原始數字 </h3>
from google.colab import files
dfO.to_excel(f'{股票代號}Original_Energy_Power.xlsx',index=False) 
files.download(f'{股票代號}Original_Energy_Power.xlsx')

## **抓取股票**

In [ ]:
#@markdown <h3> 抓取所有股票 </h3>
#@markdown <h3> 查看2330最新更新日期 </h3>
from io import BytesIO
import requests
import pandas as pd

def df_date_filter(AllStock, start, end):
        if start:
            AllStock = AllStock[AllStock['date'] >= start]
        if end:
            AllStock = AllStock[AllStock['date'] <= end]
        return AllStock

# df_date_filter(AllStock, start,end)


start= '2021-01-04'
塞選日期 =  "2021-09-09"#@param {type:"date"}
mLink = 'https://github.com/williamlikesweet/twstock_database/blob/main/history/AllStock.csv?raw=true'
AllStock = pd.read_csv(mLink)
AllStock['stock_id'] = AllStock['stock_id'].astype(str)
AllStock = df_date_filter(AllStock, start,塞選日期)
AllStock[AllStock['stock_id']=='2330'].iloc[-1:]

       stock_id        date    開盤價    收盤價    最低價    最高價      成交股數
242984     2330  2021-08-03  594.0  594.0  590.0  594.0  28104984

## **塞選**

In [ ]:
import pandas as pd
import talib
import numpy as np
from talib import abstract
from talib import MA_Type
from talib import ULTOSC
import matplotlib.pyplot as plt

Basic_name = pd.read_csv('https://raw.githubusercontent.com/williamlikesweet/twstock_database/main/history/basic.csv?raw=true')
Basic_name = Basic_name[['stock_id','公司簡稱','交易市場','產業別','主要經營業務']]
Basic_name['stock_id'] = Basic_name['stock_id'].astype(str)
Basic_name.set_index("stock_id" , inplace=True)

def talib_all_stock(AllStock, func, **args):
    isSeries = True if len(func.output_names) == 1 else False
    names = func.output_names
    if isSeries:
        dic = {}
    else:
        dics = {n:{} for n in names}
        
    open_ = AllStock.pivot_table('開盤價','date','stock_id')
    close = AllStock.pivot_table('收盤價','date','stock_id')
    high = AllStock.pivot_table('最高價','date','stock_id')
    low = AllStock.pivot_table('最低價','date','stock_id')
    volume = AllStock.pivot_table('成交股數','date','stock_id')

    for key in close.columns:
        try:
            s = func({'open':open_[key].ffill(),
                           'high':high[key].ffill(),
                           'low':low[key].ffill(),
                           'close':close[key].ffill(),
                           'volume':volume[key].ffill()}, **args)
        except Exception as e:
            if "inputs are all NaN" != str(e):
                print('Warrning occur during calculating stock '+key+':',e)
                print('The indicator values are set to NaN.')
            if isSeries:
                s = pd.Series(index=close[key].index)
            else:
                s = pd.DataFrame(index=close[key].index, columns=dics.keys())

        if isSeries:
            dic[key] = s
        else:
            for colname, si in zip(names, s):
                dics[colname][key] = si
   
    if isSeries:
        ret = pd.DataFrame(dic, index=close.index)
    else:
        newdic = {}
        for key, dic in dics.items():
            newdic[key] = pd.DataFrame(dic, close.index)
        ret = [newdic[n] for n in names]#pd.Panel(newdic)
    return ret


def strategy_1(AllStock):
    
    a0 = AllStock.pivot_table('成交股數','date','stock_id').iloc[-1] > 200*1000

    EMA7 = talib_all_stock(AllStock,abstract.EMA,timeperiod=7)
    EMA21 = talib_all_stock(AllStock ,abstract.EMA,timeperiod=21)
    EMA56 = talib_all_stock(AllStock ,abstract.EMA,timeperiod=56)

    ##################################################################
    # 塞選條件
    ##################################################################

    Green = (EMA7.iloc[-1] > EMA21.iloc[-1])& (EMA7.iloc[-2] < EMA21.iloc[-2])

    s1 = (EMA7.iloc[-1] > EMA21.iloc[-1])
    s2 = EMA7.iloc[-1] > EMA56.iloc[-1]
    s3 = (EMA21.iloc[-1]> EMA56.iloc[-1]) & (EMA56.iloc[-2] > EMA21.iloc[-2])
    Sun = (s1&s2&s3)
    
    h = AllStock.pivot_table('最高價','date','stock_id')
    l = AllStock.pivot_table('最低價','date','stock_id')
    c = AllStock.pivot_table('收盤價','date','stock_id')
    ap = (h+l+c)/3
    ap = ap.fillna(0)
    esa = ap.apply(lambda c: talib.EMA(c, 10))
    d = abs(ap - esa).apply(lambda c: talib.EMA(c, 10))
    ci = (ap - esa) / (0.015 * d)
    tci = ci.apply(lambda c: talib.EMA(c, 21))
    tci = tci.dropna(axis=1,how='all')
    wt1 = tci
    wt2 = wt1.apply(lambda c: talib.SMA(c, 4))
    
    Long = (wt1.iloc[-1] > wt2.iloc[-1]) & (wt1.iloc[-2] < wt2.iloc[-2]) & (wt1.iloc[-1] < -40)
    short = (wt1.iloc[-1] < wt2.iloc[-1]) & (wt1.iloc[-2] > wt2.iloc[-2]) & (wt2.iloc[-1] > 40)
    
    Filter = "Long" #@param ["Green", "Sun", "Long"]

    if Filter=='Green':
      condition =a0 & Green
    if Filter=='Sun':
      condition =a0 & Sun
    if Filter=='Long':
      condition =a0 & Long

    return condition[condition]
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
allfilters = strategy_1(AllStock)
allfilters = allfilters.reset_index()[['stock_id']]
allfilters = pd.merge(allfilters,Basic_name,on='stock_id',how='left')
allfilters

stock_id
1459    True
1762    True
2038    True
2103    True
2417    True
2425    True
2492    True
2832    True
3287    True
3540    True
3622    True
3630    True
3669    True
4167    True
4904    True
5452    True
6504    True
8905    True
9136    True
9958    True
dtype: bool

## **台股漲跌與市值板塊圖**

In [ ]:
import pandas as pd
import plotly.express as px
import numpy as np
import random
basic2_info = pd.read_csv('https://raw.githubusercontent.com/williamlikesweet/twstock_database/main/history/basic2.csv?raw=true')
basic2_info['實收資本額(元)'] = basic2_info['實收資本額(元)'].apply(int)
basic2_info = basic2_info.rename(columns={'公司代號': 'stock_id'})

close = AllStock.pivot_table('收盤價','date','stock_id')
price = AllStock.pivot_table('成交金額','date','stock_id')


class TwStockTreeMap:

    def __init__(self, close,price, basic2_info, start=None, end=None):
        self.start = start
        self.end = end
        self.close = close
        self.price = price
        self.basic2_info = basic2_info

    # dataframe filter by selected date
    def df_date_filter(self, df, start=None, end=None):
        if start:
            df = df[df.index >= start]
        if end:
            df = df[df.index <= end]
        return df

    # map stock_name from basic info(stock_id +name)
    def map_stock_name(self, basic2_info, s):
        target = basic2_info[basic2_info['stock_id'].astype(str).str.find(s) > -1]
        if len(target) > 0:
            s = target['stock_id'].values[0]
        return s

    def create_data(self):
        close_data = self.df_date_filter(self.close, self.start, end=self.end)
        price_data = self.df_date_filter(self.price, self.start, end=self.end)
        return_ratio = (close_data.iloc[-1] / close_data.iloc[0]).dropna().replace(np.inf, 0)
        return_ratio = round((return_ratio - 1) * 100, 2)
        return_ratio = pd.concat([return_ratio, close_data.iloc[-1]], axis=1).dropna()
        return_ratio = return_ratio.reset_index()
        return_ratio.columns = ['stock_id', 'return_ratio','close']
        price_value = price_data.astype(float)
        price_value = pd.DataFrame(price_value[0:].sum(0))
        price_value = price_value.reset_index()
        price_value = price_value.rename(columns={0: 'price'})
        return_ratio = return_ratio.merge(price_value, how='left',on='stock_id')
        return_ratio['stock_id'] = return_ratio['stock_id'].apply(lambda s: self.map_stock_name(basic2_info, s))
        return_ratio = return_ratio.merge(self.basic2_info[['stock_id','公司簡稱','產業類別', '交易市場', '實收資本額(元)']], how='left',
                                          on='stock_id')
        return_ratio = return_ratio.rename(columns={'產業類別': 'category','公司簡稱':'CoLtd' ,'交易市場': 'market', '實收資本額(元)': 'base'})
        return_ratio['market_value'] = round(return_ratio['base'] / 10 * return_ratio['close'] / 100000000, 2)
        return_ratio = return_ratio.dropna(thresh=5)
        return_ratio['country'] = 'TW-Stock'
        return return_ratio

    def create_fig(self, relative_market_strength=False):
        df = self.create_data()
        if relative_market_strength is True:
            color_continuous_midpoint = np.average(df['return_ratio'], weights=df['base'])
        else:
            color_continuous_midpoint = 0
            
        #顏色
        colorscale = [
                        #跌
                        [0, 'rgb(0, 120, 0)'], 
                        #平
                        [0.5, 'rgb(65, 70, 79)'],
                        #漲
                        [1, 'rgb(231, 72, 78)']
                    ]
        fig = px.treemap(df, path=['country', 'market', 'category', 'stock_id'], values='price',
                         color='return_ratio',
                         color_continuous_scale=colorscale,
                         color_continuous_midpoint=color_continuous_midpoint,
                         title=f"TW-Stock Market TreeMap({self.start}~{self.end})")
        
        fig.update_traces(textposition='middle center', textfont_size=24,
#                         texttemplate= "%{label}<br>%{customdata[0]}<br>%{customdata[1]})"
                        )
        fig.data[0].textinfo = 'label'
        Price = df.price.tolist()
        Close = df.close.tolist()
        CoLtd = df.CoLtd.tolist()
        fig.data[0].customdata = np.column_stack([Close,CoLtd,Price])
        
        fig.data[0].hovertemplate='<b></b>公司代號:%{label}'+'<br>公司簡稱:%{customdata[1]}'+'<br>漲跌幅:%{color}'+'<br>股價:%{customdata[0]}'+'<br>成交金額:%{customdata[2]}'
        fig.update_layout(width=1350, height=900)
        return fig
    
start= '2021-09-21' #@param {type:"date"}
end = '2021-09-23' #@param {type:"date"}
relative_market_strength = "True" #@param ["False", "True"] {type:"raw"}
TwStockTreeMap(close,price,basic2_info,start,end).create_fig(relative_market_strength)